Tiers.WebApi/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;

namespace Tiers.WebApi.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }
    }
}

Tiers.WebApi/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using Tiers.WebApi.Areas.HelpPage.Models;

namespace Tiers.WebApi.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

Tiers.WebApi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Tiers.WebApi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Tiers.WebApi/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Tiers.Core;
using Tiers.Service;

namespace Tiers.WebApi.Controllers
{
    public class UsersController : ApiController
    {
        // GET api/user
        public IEnumerable<UserDTO> Get()
        {
            return new UserService().GetAll();
        }

        // GET api/user/id
        public UserDTO Get(int id)
        {
            return new UserService().Get(id);
        }

        // POST api/user
        public HttpResponseMessage Post([FromBody]UserDTO user)
        {
            if (ModelState.IsValid)
            {
                user = new UserService().Create(user);
                if (Request != null) // Skip response if Request is null (unit testing)
                {
                    var response = 
                        Request.CreateResponse<UserDTO>(HttpStatusCode.Created, user);

                    string uri = Url.Link("DefaultApi", new { id = user.ID });
                    response.Headers.Location = new Uri(uri);
                    return response;
                }
            }
            else
            {
                return 
                    Request.CreateErrorResponse(HttpStatusCode.BadRequest, ModelState);
            }

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        // PUT api/values/user
        public UserDTO Put(int id, [FromBody]string value)
        {
            return new UserService().Update(new UserDTO() { ID = id, Name = value });
        }

        // DELETE api/values/id
        public int Delete(int id)
        {
            return new UserService().Delete(id);
        }
    }
}

Tiers.WebApi/Views/Home/Index.cshtml
<div id="body">
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>Tiers Web API - </h1>
                <h2>This WebApi project serves simple data to the rest of the UI applications in the solution.</h2>
            </hgroup>
            <p>
                
            </p>
            <p>
                To learn more about ASP.NET Web API visit the
                <a href="http://go.microsoft.com/fwlink/?LinkID=238195" title="ASP.NET Web API Website">ASP.NET Web API Website</a>.
                The page features <mark>videos, tutorials, and samples</mark> to help you get the most from ASP.NET Web API.
                If you have any questions about ASP.NET Web API, visit
                <a href="http://go.microsoft.com/fwlink/?LinkID=238196" title="ASP.NET Web API Forum">our forums</a>.
            </p>
        </div>
    </section>
    <section class="content-wrapper main-content clear-fix">
        <h3>Now that WebApi is loaded, you can try running the other UIs (but don't close this Visual Studio instance):</h3>
        <ol class="round">
            <li class="one">
                <br />
                    <a href="http://localhost:49574">WebForms</a>
                <br />
                <br />
                    <a href="http://localhost:58808">MVC</a>
                <br />
            </li>
            <li class="two">
                <br />
                    <a href="http://localhost:52183">AngularJS</a>
                <br />
                <h5>
                    WinForms (start from Visual Studio)
                </h5>
            </li>
            <li class="three">
                <h5>
                    WPF (start from Visual Studio)
                </h5>
                <h5>
                    Console (start from Visual Studio)
                </h5>
            </li>
        </ol>
    </section>
</div>

Tiers.WebApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">
                    <a href="~/">ASP.NET Web API</a></p>
            </div>
            <div class="float-right">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>